import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface OrderData {
  manufacturer: string;
  dealerInfo: {
    dealerName: string;
    dealerNumber: string;
    orderedBy: string;
    email: string;
    shippingAddress: string;
    phone: string;
    poNumber: string;
    orderDate: string;
    paymentMethod: string;
  };
  series: string;
  seriesId: string;
  model: string;
  modelId: string;
  dealerCost: number;
  msrp: number;
  shellColor: string;
  shellColorCode: string;
  shellUpcharge: number;
  cabinetColor: string;
  cabinetColorCode: string;
  cover: string;
  coverPrice: number;
  steps: { name: string; price: number }[];
  stepColor: string | null;
  options: { name: string; price: number }[];
  notes: string;
  freight: number;
  lineItemTotal: number;
  subtotal: number;
  discount: number;
  total: number;
}

export function generatePdf(data: OrderData): Uint8Array {
  const doc = new jsPDF({ format: 'letter' });
  const mfr = data.manufacturer === 'marquis' ? 'Marquis' : 'Sundance';
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`${mfr} Spa Order`, 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`PO #: ${data.dealerInfo.poNumber}`, pageWidth - 14, 22, { align: 'right' });
  doc.text(`Date: ${data.dealerInfo.orderDate}`, pageWidth - 14, 28, { align: 'right' });

  // Dealer info table
  autoTable(doc, {
    startY: 35,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 35 } },
    body: [
      ['PO #:', data.dealerInfo.poNumber],
      ['Dealer:', `${data.dealerInfo.dealerName} (#${data.dealerInfo.dealerNumber})`],
      ['Ordered By:', `${data.dealerInfo.orderedBy} (${data.dealerInfo.email})`],
      ['Ship To:', data.dealerInfo.shippingAddress],
      ['Phone:', data.dealerInfo.phone],
      ['Payment:', data.dealerInfo.paymentMethod],
    ],
  });

  // Spa details
  const afterDealer = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 75;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Spa Configuration', 14, afterDealer + 12);

  const configRows: [string, string][] = [
    ['Series', data.series],
    ['Model', `${data.model} (${data.modelId})`],
    ['Shell Color', `${data.shellColor}${data.shellColorCode ? ` (${data.shellColorCode})` : ''}`],
    ['Cabinet Color', `${data.cabinetColor}${data.cabinetColorCode ? ` (${data.cabinetColorCode})` : ''}`],
    ['Cover', data.cover],
  ];
  for (const opt of data.options) {
    configRows.push(['Option', opt.name]);
  }
  for (const step of data.steps) {
    configRows.push(['Step', `${step.name}${data.stepColor ? ` (${data.stepColor})` : ''}`]);
  }

  autoTable(doc, {
    startY: afterDealer + 16,
    theme: 'striped',
    headStyles: { fillColor: [21, 101, 166] },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
    body: configRows,
  });

  // Notes
  if (data.notes) {
    const afterConfig = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 140;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Notes:', 14, afterConfig + 10);
    doc.setFont('helvetica', 'normal');
    doc.text(data.notes, 14, afterConfig + 16, { maxWidth: pageWidth - 28 });
  }

  // Confirmation notice
  const afterNotes = data.notes
    ? (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 160
    : (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 140;
  const noticeY = data.notes ? afterNotes + 26 : afterNotes + 12;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Please send order confirmations to:', 14, noticeY);
  doc.setFont('helvetica', 'normal');
  doc.text('info@hibernation.com and jeremy@hibernation.com', 14, noticeY + 5);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Hibernation Stoves & Spas Order System', 14, pageHeight - 10);

  const arrayBuffer = doc.output('arraybuffer');
  return new Uint8Array(arrayBuffer);
}
