import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { TravisOrderData } from '@/types/travis-order';

function formatMoney(n: number): string {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

export function generateTravisPdf(data: TravisOrderData): Uint8Array {
  const doc = new jsPDF({ format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const title = data.flow === 'stoves'
    ? 'Travis Industries — Stoves / Fireplaces Order'
    : 'Travis Industries — Parts Order';

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`PO #: ${data.dealerInfo.poNumber}`, pageWidth - 14, 22, { align: 'right' });
  doc.text(`Date: ${data.dealerInfo.orderDate}`, pageWidth - 14, 28, { align: 'right' });

  // Dealer info table
  autoTable(doc, {
    startY: 35,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 35 } },
    body: [
      ['PO #:', data.dealerInfo.poNumber],
      ['Dealer:', `${data.dealerInfo.dealerName} (#${data.dealerInfo.dealerNumber})`],
      ['Ordered By:', `${data.dealerInfo.orderedBy} (${data.dealerInfo.email})`],
      ['Ship To:', data.dealerInfo.shippingAddress],
      ['Ship Method:', data.shipMethod],
      ['Phone:', data.dealerInfo.phone],
      ['Payment:', data.dealerInfo.paymentMethod],
    ],
  });

  const afterDealer =
    (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 75;

  // Line items table
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Items Ordered', 14, afterDealer + 12);

  const itemRows = data.lineItems.map(item => [
    item.sku,
    item.name,
    String(item.qty),
    formatMoney(item.unitPrice),
    formatMoney(item.lineTotal),
  ]);

  autoTable(doc, {
    startY: afterDealer + 16,
    theme: 'striped',
    headStyles: { fillColor: [21, 101, 166] },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { cellWidth: 30 },  // SKU
      2: { cellWidth: 15, halign: 'center' },  // Qty
      3: { cellWidth: 25, halign: 'right' },   // Unit
      4: { cellWidth: 25, halign: 'right' },   // Total
    },
    head: [['SKU', 'Description', 'Qty', 'Unit', 'Line Total']],
    body: itemRows,
    foot: [
      [
        { content: 'Subtotal', colSpan: 4, styles: { halign: 'right', fontStyle: 'bold' } },
        { content: formatMoney(data.subtotal), styles: { halign: 'right', fontStyle: 'bold' } },
      ],
      ...(data.freight > 0 ? [[
        { content: 'Freight', colSpan: 4, styles: { halign: 'right' } },
        { content: formatMoney(data.freight), styles: { halign: 'right' } },
      ]] : []),
      [
        { content: 'Total', colSpan: 4, styles: { halign: 'right', fontStyle: 'bold', fillColor: [230, 230, 230] } },
        { content: formatMoney(data.total), styles: { halign: 'right', fontStyle: 'bold', fillColor: [230, 230, 230] } },
      ],
    ],
  });

  const afterItems =
    (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 160;

  // Order notes
  if (data.orderNotes) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Order Notes:', 14, afterItems + 10);
    doc.setFont('helvetica', 'normal');
    doc.text(data.orderNotes, 14, afterItems + 16, { maxWidth: pageWidth - 28 });
  }

  // Confirmation notice
  const noticeY = data.orderNotes ? afterItems + 30 : afterItems + 12;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Please send order confirmations to:', 14, noticeY);
  doc.setFont('helvetica', 'normal');
  doc.text('info@hibernation.com and jeremy@hibernation.com', 14, noticeY + 5);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Hibernation Stoves & Spas Order System', 14, pageHeight - 10);

  const arrayBuffer = doc.output('arraybuffer');
  return new Uint8Array(arrayBuffer);
}
