import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { generateTravisPdf } from '@/lib/travis-pdf';
import { saveOrder } from '@/lib/kv';
import type { StoredOrder } from '@/types/order-history';
import type { TravisOrderData } from '@/types/travis-order';

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

function buildEmailHtml(data: TravisOrderData): string {
  const itemRows = data.lineItems.map(item => `
    <tr>
      <td style="padding:4px 8px;border:1px solid #ddd;font-family:monospace;font-size:12px">${item.sku}</td>
      <td style="padding:4px 8px;border:1px solid #ddd">${item.name}</td>
      <td style="padding:4px 8px;border:1px solid #ddd;text-align:center">${item.qty}</td>
      <td style="padding:4px 8px;border:1px solid #ddd;text-align:right">$${item.unitPrice.toFixed(2)}</td>
      <td style="padding:4px 8px;border:1px solid #ddd;text-align:right">$${item.lineTotal.toFixed(2)}</td>
    </tr>
  `).join('');

  return `
    <div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;color:#333">
      <h2 style="color:#1565a6;margin-bottom:4px">Travis Industries — Stoves / Fireplaces Order</h2>
      <p style="color:#666;margin-top:0">PO #${data.dealerInfo.poNumber} &middot; ${data.dealerInfo.orderDate}</p>

      <table style="width:100%;border-collapse:collapse;margin-bottom:16px">
        <tr><td style="padding:4px 8px;font-weight:bold;width:130px">PO #</td><td style="padding:4px 8px">${data.dealerInfo.poNumber}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Dealer</td><td style="padding:4px 8px">${data.dealerInfo.dealerName} (#${data.dealerInfo.dealerNumber})</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Ordered By</td><td style="padding:4px 8px">${data.dealerInfo.orderedBy}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Ship To</td><td style="padding:4px 8px">${data.dealerInfo.shippingAddress}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Ship Method</td><td style="padding:4px 8px">${data.shipMethod}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Payment</td><td style="padding:4px 8px">${data.dealerInfo.paymentMethod}</td></tr>
      </table>

      <h3 style="color:#1565a6;border-bottom:2px solid #1565a6;padding-bottom:4px">Items Ordered</h3>
      <table style="width:100%;border-collapse:collapse;margin-bottom:16px;font-size:13px">
        <thead>
          <tr style="background:#f5f5f5">
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:left">SKU</th>
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:left">Description</th>
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:center">Qty</th>
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:right">Unit</th>
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:right">Total</th>
          </tr>
        </thead>
        <tbody>${itemRows}</tbody>
        <tfoot>
          <tr>
            <td colspan="4" style="padding:4px 8px;text-align:right;border:1px solid #ddd;font-weight:bold">Subtotal</td>
            <td style="padding:4px 8px;text-align:right;border:1px solid #ddd;font-weight:bold">$${data.subtotal.toFixed(2)}</td>
          </tr>
          ${data.freight > 0 ? `<tr>
            <td colspan="4" style="padding:4px 8px;text-align:right;border:1px solid #ddd">Freight</td>
            <td style="padding:4px 8px;text-align:right;border:1px solid #ddd">$${data.freight.toFixed(2)}</td>
          </tr>` : ''}
          <tr style="background:#f5f5f5">
            <td colspan="4" style="padding:6px 8px;text-align:right;border:1px solid #ddd;font-weight:bold">Total</td>
            <td style="padding:6px 8px;text-align:right;border:1px solid #ddd;font-weight:bold">$${data.total.toFixed(2)}</td>
          </tr>
        </tfoot>
      </table>

      ${data.orderNotes ? `<p style="background:#f5f5f5;padding:12px;border-radius:4px"><strong>Order Notes:</strong> ${data.orderNotes}</p>` : ''}

      <p style="margin-top:20px;font-size:13px"><strong>Please send order confirmations to:</strong><br/>info@hibernation.com and jeremy@hibernation.com</p>

      <p style="color:#999;font-size:12px;margin-top:24px">Generated by Hibernation Stoves &amp; Spas Order System</p>
    </div>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const data: TravisOrderData = await request.json();

    if (!data.lineItems || data.lineItems.length === 0) {
      return NextResponse.json({ error: 'No line items' }, { status: 400 });
    }
    if (!data.dealerInfo?.poNumber) {
      return NextResponse.json({ error: 'PO number required' }, { status: 400 });
    }

    const pdfBytes = generateTravisPdf(data);
    const filename = `Hibernation_PO_${data.dealerInfo.poNumber}_Travis_Stoves.pdf`;

    await transporter.sendMail({
      from: `"Hibernation Orders" <${process.env.GMAIL_USER}>`,
      to: 'saleswest@travisindustries.com',
      cc: ['info@hibernation.com', 'jeremy@hibernation.com'],
      subject: `New Order - Hibernation PO# ${data.dealerInfo.poNumber} - Travis Stoves`,
      html: buildEmailHtml(data),
      attachments: [
        { filename, content: Buffer.from(pdfBytes), contentType: 'application/pdf' },
      ],
    });

    // Save to order history (non-critical — email already sent).
    const orderId = crypto.randomUUID();
    const itemCount = data.lineItems.reduce((sum, i) => sum + i.qty, 0);
    const storedOrder: StoredOrder = {
      id: orderId,
      type: 'stove',
      vendor: 'travis-stoves',
      status: 'submitted',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      poNumber: data.dealerInfo.poNumber,
      orderDate: data.dealerInfo.orderDate,
      orderedBy: data.dealerInfo.orderedBy,
      description: `Travis Stoves — ${itemCount} item${itemCount !== 1 ? 's' : ''}`,
      total: data.total,
      freight: data.freight,
      orderData: data as unknown as Record<string, unknown>,
    };
    try {
      await saveOrder(storedOrder);
    } catch (kvError) {
      console.error('Failed to save Travis stoves order to KV (email sent):', kvError);
    }

    return NextResponse.json({ success: true, orderId });
  } catch (err) {
    console.error('Send Travis stoves order error:', err);
    const message = err instanceof Error ? err.message : 'Failed to send order';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
