import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { generatePdf, OrderData } from '@/lib/pdf';

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

function buildEmailHtml(data: OrderData): string {
  const mfr = data.manufacturer === 'marquis' ? 'Marquis' : 'Sundance';

  const configRows = [
    ['Series', data.series],
    ['Model', `${data.model} (${data.modelId})`],
    ['Shell Color', `${data.shellColor}${data.shellColorCode ? ` (${data.shellColorCode})` : ''}`],
    ['Cabinet Color', `${data.cabinetColor}${data.cabinetColorCode ? ` (${data.cabinetColorCode})` : ''}`],
    ['Cover', data.cover],
  ];
  for (const opt of data.options) {
    configRows.push(['Option', opt.name]);
  }
  for (const step of data.steps) {
    configRows.push(['Step', `${step.name}${data.stepColor ? ` (${data.stepColor})` : ''}`]);
  }

  const configHtml = configRows.map(([label, value]) =>
    `<tr><td style="padding:4px 8px;font-weight:bold;width:120px">${label}</td><td style="padding:4px 8px">${value}</td></tr>`
  ).join('');

  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#333">
      <h2 style="color:#1565a6;margin-bottom:4px">${mfr} Spa Order</h2>
      <p style="color:#666;margin-top:0">PO #${data.dealerInfo.poNumber} &middot; ${data.dealerInfo.orderDate}</p>

      <table style="width:100%;border-collapse:collapse;margin-bottom:16px">
        <tr><td style="padding:4px 8px;font-weight:bold;width:120px">PO #</td><td style="padding:4px 8px">${data.dealerInfo.poNumber}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Dealer</td><td style="padding:4px 8px">${data.dealerInfo.dealerName} (#${data.dealerInfo.dealerNumber})</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Ordered By</td><td style="padding:4px 8px">${data.dealerInfo.orderedBy}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Ship To</td><td style="padding:4px 8px">${data.dealerInfo.shippingAddress}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Payment</td><td style="padding:4px 8px">${data.dealerInfo.paymentMethod}</td></tr>
      </table>

      <h3 style="color:#1565a6;border-bottom:2px solid #1565a6;padding-bottom:4px">Spa Configuration</h3>
      <table style="width:100%;border-collapse:collapse;margin-bottom:16px">${configHtml}</table>

      ${data.notes ? `<p style="background:#f5f5f5;padding:12px;border-radius:4px"><strong>Notes:</strong> ${data.notes}</p>` : ''}

      <p style="margin-top:20px;font-size:13px"><strong>Please send order confirmations to:</strong><br/>info@hibernation.com and jeremy@hibernation.com</p>

      <p style="color:#999;font-size:12px;margin-top:24px">Generated by Hibernation Stoves &amp; Spas Order System</p>
    </div>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const data: OrderData = await request.json();

    // Generate PDF attachment
    const pdfBuffer = generatePdf(data);
    const filename = `Hibernation_PO_${data.dealerInfo.poNumber}_${data.model}.pdf`;

    const brandEmail = data.manufacturer === 'marquis'
      ? 'insidesales@marquiscorp.com'
      : 'orderdesk@jacuzzibrands.com';

    await transporter.sendMail({
      from: `"Hibernation Orders" <${process.env.GMAIL_USER}>`,
      to: brandEmail,
      cc: ['info@hibernation.com', 'jeremy@hibernation.com'],
      subject: `New Order - Hibernation PO# ${data.dealerInfo.poNumber} - ${data.model}`,
      html: buildEmailHtml(data),
      attachments: [
        {
          filename,
          content: Buffer.from(pdfBuffer),
          contentType: 'application/pdf',
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Send order error:', error);
    const message = error instanceof Error ? error.message : 'Failed to send order';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
