import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { AccessoryOrderData } from '@/types/accessories';
import { saveOrder } from '@/lib/kv';
import { StoredOrder } from '@/types/order-history';

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

function buildEmailHtml(data: AccessoryOrderData): string {
  const itemRows = data.lineItems.map(item => {
    const variantPart = item.variantLabel ? ` — <em>${item.variantLabel}</em>` : '';
    const skuPart = item.sku ? ` (${item.sku})` : '';
    return `<tr>
      <td style="padding:4px 8px;border:1px solid #ddd">${item.name}${variantPart}${skuPart}</td>
      <td style="padding:4px 8px;border:1px solid #ddd;text-align:center">${item.quantity}</td>
      <td style="padding:4px 8px;border:1px solid #ddd;text-align:right">$${item.price.toFixed(2)}</td>
      <td style="padding:4px 8px;border:1px solid #ddd;text-align:right">$${item.lineTotal.toFixed(2)}</td>
    </tr>`;
  }).join('');

  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#333">
      <h2 style="color:#1565a6;margin-bottom:4px">${data.vendorName} — Accessories Order</h2>
      <p style="color:#666;margin-top:0">PO #${data.dealerInfo.poNumber} &middot; ${data.dealerInfo.orderDate}</p>

      <table style="width:100%;border-collapse:collapse;margin-bottom:16px">
        <tr><td style="padding:4px 8px;font-weight:bold;width:120px">PO #</td><td style="padding:4px 8px">${data.dealerInfo.poNumber}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Dealer</td><td style="padding:4px 8px">${data.dealerInfo.dealerName}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Ordered By</td><td style="padding:4px 8px">${data.dealerInfo.orderedBy}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Ship To</td><td style="padding:4px 8px">${data.dealerInfo.shippingAddress}</td></tr>
        <tr><td style="padding:4px 8px;font-weight:bold">Payment</td><td style="padding:4px 8px">${data.dealerInfo.paymentMethod}</td></tr>
      </table>

      <h3 style="color:#1565a6;border-bottom:2px solid #1565a6;padding-bottom:4px">Items Ordered</h3>
      <table style="width:100%;border-collapse:collapse;margin-bottom:16px">
        <thead>
          <tr style="background:#f5f5f5">
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:left">Item</th>
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:center">Qty</th>
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:right">Unit Price</th>
            <th style="padding:6px 8px;border:1px solid #ddd;text-align:right">Total</th>
          </tr>
        </thead>
        <tbody>${itemRows}</tbody>
        <tfoot>
          <tr>
            <td colspan="3" style="padding:4px 8px;font-weight:bold;text-align:right;border:1px solid #ddd">Subtotal</td>
            <td style="padding:4px 8px;font-weight:bold;text-align:right;border:1px solid #ddd">$${data.subtotal.toFixed(2)}</td>
          </tr>
          ${data.freight > 0 ? `<tr>
            <td colspan="3" style="padding:4px 8px;text-align:right;border:1px solid #ddd">Freight</td>
            <td style="padding:4px 8px;text-align:right;border:1px solid #ddd">$${data.freight.toFixed(2)}</td>
          </tr>` : ''}
          <tr style="background:#f5f5f5">
            <td colspan="3" style="padding:6px 8px;font-weight:bold;text-align:right;border:1px solid #ddd">Total</td>
            <td style="padding:6px 8px;font-weight:bold;text-align:right;border:1px solid #ddd">$${data.total.toFixed(2)}</td>
          </tr>
        </tfoot>
      </table>

      ${data.notes ? `<p style="background:#f5f5f5;padding:12px;border-radius:4px"><strong>Notes:</strong> ${data.notes}</p>` : ''}

      <p style="margin-top:20px;font-size:13px"><strong>Please send order confirmations to:</strong><br/>info@hibernation.com and jeremy@hibernation.com</p>

      <p style="color:#999;font-size:12px;margin-top:24px">Generated by Hibernation Stoves &amp; Spas Order System</p>
    </div>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const data: AccessoryOrderData = await request.json();

    const toEmail = data.orderEmail || 'info@hibernation.com';

    await transporter.sendMail({
      from: `"Hibernation Orders" <${process.env.GMAIL_USER}>`,
      to: toEmail,
      cc: ['info@hibernation.com', 'jeremy@hibernation.com'],
      subject: `Accessories Order - Hibernation PO# ${data.dealerInfo.poNumber} - ${data.vendorName}`,
      html: buildEmailHtml(data),
    });

    // Save to order history
    const orderId = crypto.randomUUID();
    const itemCount = data.lineItems.reduce((sum, item) => sum + item.quantity, 0);
    const storedOrder: StoredOrder = {
      id: orderId,
      type: 'supplies',
      vendor: data.vendorId,
      status: 'submitted',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      poNumber: data.dealerInfo.poNumber,
      orderDate: data.dealerInfo.orderDate,
      orderedBy: data.dealerInfo.orderedBy,
      description: `${data.vendorName} — ${itemCount} item${itemCount !== 1 ? 's' : ''}`,
      total: data.total,
      freight: data.freight,
      orderData: data as unknown as Record<string, unknown>,
    };
    try {
      await saveOrder(storedOrder);
    } catch (kvError) {
      console.error('Failed to save accessories order to KV:', kvError);
    }

    return NextResponse.json({ success: true, orderId });
  } catch (error) {
    console.error('Send accessories order error:', error);
    const message = error instanceof Error ? error.message : 'Failed to send order';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
