/**
 * Travis Industries catalog — unified read surface.
 *
 * Combines:
 *   - travisStoves  (AUTO-GENERATED by scripts/import-travis.py)
 *   - travisParts   (AUTO-GENERATED)
 *   - travisPartsManual (hand-maintained / GH-Actions-sync target)
 *
 * Runtime KV pending-additions are NOT merged here — that happens in the API
 * routes (Plan 2 & 3) so this module stays synchronous and pure.
 */
import { TravisProduct } from '@/types/travis';
import { travisStoves } from './stoves';
import { travisParts } from './parts';
import { travisPartsManual } from './parts-manual';

/** All Travis products, deduplicated by SKU (manual > parts > stoves wins on conflict). */
export const travisCatalog: TravisProduct[] = dedupeBySKU([
  ...travisStoves,
  ...travisParts,
  ...travisPartsManual,
]);

/** Indexed lookup, built once at module load. */
const BY_SKU: Map<string, TravisProduct> = new Map(
  travisCatalog.map(p => [p.sku.toUpperCase(), p])
);

export function findTravisProduct(sku: string): TravisProduct | undefined {
  return BY_SKU.get(sku.trim().toUpperCase());
}

/**
 * Search by SKU prefix or name substring. Returns up to `limit` matches,
 * with SKU-prefix matches ranked ahead of name matches.
 */
export function searchTravisProducts(query: string, limit = 20): TravisProduct[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const skuMatches: TravisProduct[] = [];
  const nameMatches: TravisProduct[] = [];

  for (const p of travisCatalog) {
    if (p.sku.toLowerCase().startsWith(q)) {
      skuMatches.push(p);
    } else if (p.name.toLowerCase().includes(q)) {
      nameMatches.push(p);
    }
    if (skuMatches.length >= limit) break;
  }

  return [...skuMatches, ...nameMatches].slice(0, limit);
}

function dedupeBySKU(products: TravisProduct[]): TravisProduct[] {
  const seen = new Map<string, TravisProduct>();
  for (const p of products) {
    // Later entries win — that's why the input order is stoves → parts → manual.
    seen.set(p.sku.toUpperCase(), p);
  }
  return Array.from(seen.values());
}

export { travisStoves, travisParts, travisPartsManual };
